"""
Demo File Generator for Deepurge AutoClean Agent
Creates 50 test files of various types for demonstration purposes

Author: Samuel Campozano Lopez
Project: Sui Hackathon 2026

Usage:
    python demo_generator.py [target_folder]
    
Example:
    python demo_generator.py ~/Downloads
"""

import os
import sys
import json
import random
import string
from pathlib import Path
from datetime import datetime, timedelta
from colorama import init, Fore, Style

# Initialize colorama
init(autoreset=True)


class DemoFileGenerator:
    """Generates various test files for demonstration"""
    
    # File templates
    TEMPLATES = {
        # Images (simulated with small binary data)
        "Images": {
            "extensions": [".jpg", ".png", ".gif", ".webp"],
            "names": ["vacation_photo", "screenshot", "profile_pic", "wallpaper", "meme", "selfie", "landscape", "product_image"],
            "content_type": "binary"
        },
        # Documents
        "Documents": {
            "extensions": [".pdf", ".txt", ".md", ".docx"],
            "names": ["report", "invoice", "resume", "notes", "contract", "meeting_minutes", "proposal", "readme"],
            "content_type": "text"
        },
        # Videos (simulated)
        "Videos": {
            "extensions": [".mp4", ".mkv", ".avi"],
            "names": ["tutorial", "gameplay", "vlog", "presentation", "demo_video", "screen_recording"],
            "content_type": "binary"
        },
        # Audio (simulated)
        "Audio": {
            "extensions": [".mp3", ".wav", ".flac"],
            "names": ["podcast", "song", "voice_memo", "sound_effect", "audiobook", "interview"],
            "content_type": "binary"
        },
        # Code
        "Code": {
            "extensions": [".py", ".js", ".html", ".css", ".json"],
            "names": ["script", "component", "utils", "config", "handler", "module", "test"],
            "content_type": "code"
        },
        # Archives (simulated)
        "Archives": {
            "extensions": [".zip", ".rar", ".tar.gz"],
            "names": ["backup", "project_files", "assets", "archive", "bundle", "package"],
            "content_type": "binary"
        }
    }
    
    # Sample content for text files
    TEXT_CONTENT = [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "The quick brown fox jumps over the lazy dog.",
        "This is a sample document created for testing purposes.",
        "Deepurge AutoClean Agent - File Organization Demo",
        "Sui Hackathon 2026 - Samuel Campozano Lopez",
        "Walrus decentralized storage integration test file.",
    ]
    
    # Sample code content
    CODE_TEMPLATES = {
        ".py": '''"""
Sample Python Script
Generated by Deepurge Demo Generator
"""

def hello_world():
    """Print hello world message"""
    print("Hello from Deepurge AutoClean Agent!")
    return True

if __name__ == "__main__":
    hello_world()
''',
        ".js": '''/**
 * Sample JavaScript File
 * Generated by Deepurge Demo Generator
 */

function helloWorld() {
    console.log("Hello from Deepurge AutoClean Agent!");
    return true;
}

module.exports = { helloWorld };
''',
        ".html": '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deepurge Demo</title>
</head>
<body>
    <h1>Deepurge AutoClean Agent Demo</h1>
    <p>This file was generated for testing purposes.</p>
</body>
</html>
''',
        ".css": '''/* 
 * Sample CSS File
 * Generated by Deepurge Demo Generator
 */

body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
    background-color: #f5f5f5;
}

h1 {
    color: #333;
}
''',
        ".json": '''{
    "name": "deepurge-demo",
    "version": "1.0.0",
    "description": "Demo file generated by Deepurge AutoClean Agent",
    "author": "Samuel Campozano Lopez",
    "license": "MIT"
}
'''
    }
    
    def __init__(self, target_folder: Path):
        self.target_folder = Path(target_folder).expanduser()
        self.generated_files = []
    
    def _random_string(self, length: int = 8) -> str:
        """Generate a random string"""
        return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))
    
    def _generate_binary_content(self, size_kb: int = 10) -> bytes:
        """Generate random binary content"""
        return os.urandom(size_kb * 1024)
    
    def _generate_text_content(self) -> str:
        """Generate text content"""
        lines = random.sample(self.TEXT_CONTENT, min(3, len(self.TEXT_CONTENT)))
        return "\n\n".join(lines) + f"\n\nGenerated: {datetime.now().isoformat()}"
    
    def _generate_code_content(self, extension: str) -> str:
        """Generate code content based on extension"""
        return self.CODE_TEMPLATES.get(extension, f"// Sample code file\n// Extension: {extension}")
    
    def generate_file(self, category: str, index: int) -> Optional[Path]:
        """Generate a single test file"""
        if category not in self.TEMPLATES:
            return None
        
        template = self.TEMPLATES[category]
        
        # Pick random name and extension
        name = random.choice(template["names"])
        extension = random.choice(template["extensions"])
        
        # Create unique filename
        filename = f"{name}_{self._random_string(4)}{extension}"
        filepath = self.target_folder / filename
        
        # Handle duplicates
        while filepath.exists():
            filename = f"{name}_{self._random_string(6)}{extension}"
            filepath = self.target_folder / filename
        
        try:
            # Generate content based on type
            if template["content_type"] == "binary":
                content = self._generate_binary_content(random.randint(5, 50))
                with open(filepath, 'wb') as f:
                    f.write(content)
            elif template["content_type"] == "code":
                content = self._generate_code_content(extension)
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
            else:  # text
                content = self._generate_text_content()
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
            
            self.generated_files.append(filepath)
            return filepath
            
        except Exception as e:
            print(f"{Fore.RED}❌ Failed to create {filename}: {e}{Style.RESET_ALL}")
            return None
    
    def generate_files(self, count: int = 50) -> list:
        """Generate multiple test files"""
        categories = list(self.TEMPLATES.keys())
        
        # Ensure folder exists
        self.target_folder.mkdir(parents=True, exist_ok=True)
        
        print(f"\n{Fore.CYAN}🎬 DEEPURGE DEMO FILE GENERATOR{Style.RESET_ALL}")
        print(f"{Fore.CYAN}{'='*50}{Style.RESET_ALL}")
        print(f"   {Fore.BLUE}Author:{Style.RESET_ALL} Samuel Campozano Lopez")
        print(f"   {Fore.BLUE}Target:{Style.RESET_ALL} {self.target_folder}")
        print(f"   {Fore.BLUE}Files to generate:{Style.RESET_ALL} {count}")
        print(f"{Fore.CYAN}{'='*50}{Style.RESET_ALL}\n")
        
        print(f"{Fore.YELLOW}📁 Generating test files...{Style.RESET_ALL}\n")
        
        # Track category counts
        category_counts = {cat: 0 for cat in categories}
        
        for i in range(count):
            # Distribute across categories
            category = categories[i % len(categories)]
            
            filepath = self.generate_file(category, i)
            
            if filepath:
                category_counts[category] += 1
                emoji = {
                    "Images": "📸",
                    "Documents": "📄",
                    "Videos": "🎬",
                    "Audio": "🎵",
                    "Code": "💻",
                    "Archives": "📦"
                }.get(category, "📁")
                
                print(f"   {emoji} [{i+1:02d}/{count}] {filepath.name}")
        
        # Print summary
        print(f"\n{Fore.GREEN}✅ Generation complete!{Style.RESET_ALL}")
        print(f"\n{Fore.CYAN}📊 Summary:{Style.RESET_ALL}")
        for category, count in category_counts.items():
            if count > 0:
                print(f"   {category}: {count} files")
        
        print(f"\n{Fore.YELLOW}💡 Tip: Run the Deepurge Agent to organize these files:{Style.RESET_ALL}")
        print(f"   python agent.py")
        
        return self.generated_files


def main():
    """Main entry point"""
    # Get target folder from args or use default
    if len(sys.argv) > 1:
        target_folder = Path(sys.argv[1]).expanduser()
    else:
        target_folder = Path.home() / "Downloads"
    
    # Get file count from args or use default
    count = 50
    if len(sys.argv) > 2:
        try:
            count = int(sys.argv[2])
        except ValueError:
            pass
    
    print(f"""
{Fore.CYAN}╔════════════════════════════════════════════════════╗
║                                                      ║
║   {Fore.WHITE}DEEPURGE AUTOCLEAN AGENT{Fore.CYAN}                         ║
║   {Fore.YELLOW}Demo File Generator{Fore.CYAN}                              ║
║                                                      ║
║   {Fore.GREEN}👤 Author: Samuel Campozano Lopez{Fore.CYAN}                ║
║   {Fore.MAGENTA}🎯 Sui Hackathon 2026{Fore.CYAN}                           ║
║                                                      ║
╚════════════════════════════════════════════════════╝{Style.RESET_ALL}
""")
    
    # Generate files
    generator = DemoFileGenerator(target_folder)
    files = generator.generate_files(count)
    
    print(f"\n{Fore.GREEN}🎉 {len(files)} demo files created in {target_folder}{Style.RESET_ALL}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
